<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $nombre
 * @property string $apellido
 * @property string $email
 * @property string $telefono
 * @property integer $entel
 * @property integer $movistar
 *
 * @property User $user
 * @property Empleado[] $empleados
 * @property Local[] $locals
 */
abstract class BaseCliente extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cliente';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cliente|Clientes', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('user_id, entel, movistar', 'numerical', 'integerOnly'=>true),
			array('nombre, apellido, email, telefono', 'length', 'max'=>45),
			array('user_id, nombre, apellido, email, telefono, entel, movistar', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, nombre, apellido, email, telefono, entel, movistar', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'empleados' => array(self::HAS_MANY, 'Empleado', 'cliente_id'),
			'locals' => array(self::HAS_MANY, 'Local', 'cliente_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'apellido' => Yii::t('app', 'Apellido'),
			'email' => Yii::t('app', 'Email'),
			'telefono' => Yii::t('app', 'Telefono'),
			'entel' => Yii::t('app', 'Entel'),
			'movistar' => Yii::t('app', 'Movistar'),
			'user' => null,
			'empleados' => null,
			'locals' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellido', $this->apellido, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('entel', $this->entel);
		$criteria->compare('movistar', $this->movistar);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}