<?php

/**
 * This is the model base class for the table "operador".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Operador".
 *
 * Columns in table "operador" available as properties of the model,
 * followed by relations of table "operador" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $nombre
 * @property string $apellido
 * @property string $email
 * @property string $telefono
 *
 * @property Atencion[] $atencions
 * @property User $user
 */
abstract class BaseOperador extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'operador';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Operador|Operadors', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('nombre, apellido, email, telefono', 'length', 'max'=>45),
			array('user_id, nombre, apellido, email, telefono', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, nombre, apellido, email, telefono', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'atencions' => array(self::HAS_MANY, 'Atencion', 'operador_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'apellido' => Yii::t('app', 'Apellido'),
			'email' => Yii::t('app', 'Email'),
			'telefono' => Yii::t('app', 'Telefono'),
			'atencions' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellido', $this->apellido, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('telefono', $this->telefono, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}