<?php

/**
 * This is the model base class for the table "estado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estado".
 *
 * Columns in table "estado" available as properties of the model,
 * followed by relations of table "estado" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $fechaInicio
 * @property string $fechaTermino
 * @property string $estado
 *
 * @property User $user
 */
abstract class BaseEstado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estado|Estados', $n);
	}

	public static function representingColumn() {
		return 'fechaInicio';
	}

	public function rules() {
		return array(
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>45),
			array('fechaInicio, fechaTermino', 'safe'),
			array('user_id, fechaInicio, fechaTermino, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, fechaInicio, fechaTermino, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'fechaInicio' => Yii::t('app', 'Fecha Inicio'),
			'fechaTermino' => Yii::t('app', 'Fecha Termino'),
			'estado' => Yii::t('app', 'Estado'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('fechaInicio', $this->fechaInicio, true);
		$criteria->compare('fechaTermino', $this->fechaTermino, true);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}