<?php

/**
 * This is the model base class for the table "cupo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cupo".
 *
 * Columns in table "cupo" available as properties of the model,
 * followed by relations of table "cupo" available as properties of the model.
 *
 * @property integer $id
 * @property string $numero
 * @property string $cupo
 * @property string $fecha
 *
 * @property Atencion[] $atencions
 * @property Recarga[] $recargas
 */
abstract class BaseCupo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cupo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cupo|Cupos', $n);
	}

	public static function representingColumn() {
		return 'numero';
	}

	public function rules() {
		return array(
			array('numero, cupo', 'length', 'max'=>45),
			array('fecha', 'safe'),
			array('numero, cupo, fecha', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, numero, cupo, fecha', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'atencions' => array(self::HAS_MANY, 'Atencion', 'cupo_id'),
			'recargas' => array(self::HAS_MANY, 'Recarga', 'cupo_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'numero' => Yii::t('app', 'Numero'),
			'cupo' => Yii::t('app', 'Cupo'),
			'fecha' => Yii::t('app', 'Fecha'),
			'atencions' => null,
			'recargas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('numero', $this->numero, true);
		$criteria->compare('cupo', $this->cupo, true);
		$criteria->compare('fecha', $this->fecha, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}