<?php

/**
 * This is the model base class for the table "empleado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empleado".
 *
 * Columns in table "empleado" available as properties of the model,
 * followed by relations of table "empleado" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $cliente_id
 * @property string $nombre
 * @property string $apellido
 * @property string $email
 *
 * @property Cliente $cliente
 * @property User $user
 * @property Recarga[] $recargas
 */
abstract class BaseEmpleado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empleado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empleado|Empleados', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('user_id, cliente_id', 'numerical', 'integerOnly'=>true),
			array('nombre, apellido, email', 'length', 'max'=>45),
			array('user_id, cliente_id, nombre, apellido, email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, cliente_id, nombre, apellido, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cliente' => array(self::BELONGS_TO, 'Cliente', 'cliente_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'recargas' => array(self::HAS_MANY, 'Recarga', 'usuario_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'cliente_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'apellido' => Yii::t('app', 'Apellido'),
			'email' => Yii::t('app', 'Email'),
			'cliente' => null,
			'user' => null,
			'recargas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('cliente_id', $this->cliente_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellido', $this->apellido, true);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}