<?php

/**
 * This is the model base class for the table "atencion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Atencion".
 *
 * Columns in table "atencion" available as properties of the model,
 * followed by relations of table "atencion" available as properties of the model.
 *
 * @property integer $id
 * @property integer $recarga_id
 * @property integer $operador_id
 * @property integer $cupo_id
 * @property string $fecha
 * @property string $tiempoRespuesta
 * @property string $estado
 * @property string $tipo
 *
 * @property Cupo $cupo
 * @property Operador $operador
 * @property Recarga $recarga
 * @property Noprepago[] $noprepagos
 */
abstract class BaseAtencion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'atencion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Atencion|Atencions', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('recarga_id, operador_id, cupo_id', 'numerical', 'integerOnly'=>true),
			array('estado, tipo', 'length', 'max'=>45),
			array('fecha, tiempoRespuesta', 'safe'),
			array('recarga_id, operador_id, cupo_id, fecha, tiempoRespuesta, estado, tipo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, recarga_id, operador_id, cupo_id, fecha, tiempoRespuesta, estado, tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cupo' => array(self::BELONGS_TO, 'Cupo', 'cupo_id'),
			'operador' => array(self::BELONGS_TO, 'Operador', 'operador_id'),
			'recarga' => array(self::BELONGS_TO, 'Recarga', 'recarga_id'),
			'noprepagos' => array(self::HAS_MANY, 'Noprepago', 'atencion_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'recarga_id' => null,
			'operador_id' => null,
			'cupo_id' => null,
			'fecha' => Yii::t('app', 'Fecha'),
			'tiempoRespuesta' => Yii::t('app', 'Tiempo Respuesta'),
			'estado' => Yii::t('app', 'Estado'),
			'tipo' => Yii::t('app', 'Tipo'),
			'cupo' => null,
			'operador' => null,
			'recarga' => null,
			'noprepagos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('recarga_id', $this->recarga_id);
		$criteria->compare('operador_id', $this->operador_id);
		$criteria->compare('cupo_id', $this->cupo_id);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('tiempoRespuesta', $this->tiempoRespuesta, true);
		$criteria->compare('estado', $this->estado, true);
		$criteria->compare('tipo', $this->tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}